# Generated by Django 3.1.2 on 2020-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201102_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
