# Generated by Django 3.1.2 on 2020-11-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_clearance_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearance',
            old_name='ordered',
            new_name='cleared',
        ),
    ]
