# Generated by Django 3.1.2 on 2020-11-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20201103_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
